## B-Aliases-Update-Manifest: regenerates DotfilesAliases.psd1 from the alias files; run it after adding or renaming a function so PowerShell can still auto-load it
function B-Aliases-Update-Manifest {
  [CmdletBinding()]
  param(
    [switch]$DryRun
  )

  $manifest = Join-Path $PSScriptRoot 'DotfilesAliases.psd1'
  $functions = [System.Collections.Generic.List[string]]::new()
  $aliases = [System.Collections.Generic.List[string]]::new()

  foreach ($file in (Get-ChildItem -LiteralPath $PSScriptRoot -Recurse -Filter *.ps1)) {
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($file.FullName, [ref]$null, [ref]$null)
    $ast.FindAll({ param($node) $node -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $false) |
      ForEach-Object { $functions.Add($_.Name) }
    $ast.FindAll({ param($node) $node -is [System.Management.Automation.Language.CommandAst] -and $node.GetCommandName() -eq 'Set-Alias' }, $true) |
      ForEach-Object { $aliases.Add((BAliases-SetAliasName $_)) }
  }

  $content = BAliases-ManifestContent ($functions | Sort-Object -Unique) ($aliases | Where-Object { $_ } | Sort-Object -Unique) (BAliases-ModuleGuid $manifest)
  if ($DryRun) {
    Write-Host "Dry run: $($functions.Count) functions, $($aliases.Count) aliases; manifest not written." -ForegroundColor Yellow
    return
  }

  Set-Content -LiteralPath $manifest -Value $content -Encoding utf8
  Write-Host "Wrote $manifest" -ForegroundColor Green
  Write-Host "  $($functions.Count) functions, $($aliases.Count) aliases" -ForegroundColor DarkGray
}

# Set-Alias is called as `Set-Alias -Name x -Value y` here, but positional use has to keep working.
function BAliases-SetAliasName($command) {
  $elements = $command.CommandElements
  for ($i = 1; $i -lt $elements.Count; $i++) {
    if ($elements[$i] -is [System.Management.Automation.Language.CommandParameterAst]) {
      if ($elements[$i].ParameterName -eq 'Name' -and $i + 1 -lt $elements.Count) { return $elements[$i + 1].Value }
      continue
    }
    if ($i -eq 1) { return $elements[$i].Value }
  }
}

# The GUID identifies the module across versions, so an existing one is kept.
function BAliases-ModuleGuid($manifest) {
  if (Test-Path -LiteralPath $manifest) {
    $existing = (Import-PowerShellDataFile -LiteralPath $manifest).GUID
    if ($existing) { return $existing }
  }
  return [guid]::NewGuid().ToString()
}

function BAliases-ManifestContent($functions, $aliases, $guid) {
  $quote = { param($names) ($names | ForEach-Object { "    '$_'" }) -join "`n" }

  return @"
# Generated by B-Aliases-Update-Manifest — do not edit by hand.
# FunctionsToExport is what lets PowerShell auto-load this module when one of these names is typed,
# so it has to list every function; the profile no longer dot-sources the alias files at startup.
@{
  RootModule        = 'DotfilesAliases.psm1'
  ModuleVersion     = '1.0.0'
  GUID              = '$guid'
  Description       = 'Shell aliases from the dotfiles repo, auto-loaded on first use.'
  PowerShellVersion = '5.1'

  FunctionsToExport = @(
$(& $quote $functions)
  )

  AliasesToExport   = @(
$(& $quote $aliases)
  )

  CmdletsToExport   = @()
  VariablesToExport = @()
}
"@
}
